#!/bin/bash

# Manual Server Restart Instructions
# Since sudo requires interactive password, here are the exact commands to run

SERVER_IP="192.168.1.116"
SERVER_USER="avian"

echo "🔄 Manual Server Restart Instructions"
echo ""
echo "Please run these commands manually on the server:"
echo ""
echo "1. SSH to the server:"
echo "   ssh $SERVER_USER@$SERVER_IP"
echo ""
echo "2. Navigate to the project directory:"
echo "   cd /home/avian/avian-cybersecurity-platform-onprem"
echo ""
echo "3. Check which containers are running:"
echo "   sudo docker ps"
echo ""
echo "4. Stop the application (try each until one works):"
echo "   sudo docker-compose -f docker-compose.prod.yml down"
echo "   OR"
echo "   sudo docker-compose -f docker-compose.production.yml down"
echo ""
echo "5. Start the application:"
echo "   sudo docker-compose -f docker-compose.prod.yml up -d --build"
echo "   OR"
echo "   sudo docker-compose -f docker-compose.production.yml up -d --build"
echo ""
echo "6. Check if containers are running:"
echo "   sudo docker ps"
echo ""
echo "7. Check application logs if needed:"
echo "   sudo docker-compose -f docker-compose.prod.yml logs -f"
echo ""
echo "After restart, test at: http://$SERVER_IP:3000"
echo "Login: h@tcc.com / 12345678"